DROP TABLE IF EXISTS FRAUD;
CREATE TABLE FRAUD
(
transaction_id VARCHAR(10),
transaction_datetime DATE,	
customer_id INT,	
account_age_days INT,	
num_prev_txns INT,	
avg_transaction_amount DECIMAL(10, 2),	
amount DECIMAL(10, 2),
merchant VARCHAR(20),	
category VARCHAR(20),	
location VARCHAR(20),	
device_type VARCHAR(20),	
transaction_channel VARCHAR(20),
ip_risk_score FLOAT,	
is_fraud INT
);
SELECT * FROM FRAUD;
---Q-1-TOTAL TRANSACTIONS IN THE DATASET---
SELECT 
COUNT(*) AS TOTAL
FROM FRAUD;
---Q-2-FRAUD VS NON-FRAUD SPLIT
SELECT
IS_FRAUD,
COUNT(*) AS NET
FROM FRAUD
GROUP BY 1
---Q-3-MERCHANT RISK CHECK---
SELECT 
MERCHANT,
COUNT(*) AS NET
FROM FRAUD
WHERE IS_FRAUD = 1
GROUP BY 1
ORDER BY NET DESC
LIMIT 5
---Q-4-HIGH VALUE FRAUDS---
SELECT
TRANSACTION_ID,
AMOUNT
FROM FRAUD
WHERE IS_FRAUD = 1
AND
AMOUNT > 5000
---Q-5-LOCATION ANALYSIS---
SELECT
LOCATION,
COUNT(*) AS NET
FROM FRAUD
WHERE IS_FRAUD = 1
GROUP BY 1
---Q-6-DEVICE RISK---
SELECT 
DEVICE_TYPE,
COUNT(*) AS NET
FROM FRAUD
WHERE IS_FRAUD = 1
GROUP BY 1
---Q-7-CUSTOMER RISK PROFILING---
SELECT 
CUSTOMER_ID,
COUNT(*) AS NET
FROM FRAUD
WHERE IS_FRAUD = 1
GROUP BY 1
ORDER BY NET DESC
LIMIT 3


